GET http://localhost:5000/api/v1/todos

###

GET http://localhost:5000/api/v1/todos/38

###

POST http://localhost:5000/api/v1/todos
Content-Type: application/json

{
  "title": "Book flight",
  "description": "ZRH - AUS"
}

###

PUT http://localhost:5000/api/v1/todos/37
Content-Type: application/json

{
  "title": "Book flight",
  "description": "ZRH - IAD"
}

###

DELETE http://localhost:5000/api/v1/todos/37

###